version: "3.8"

services:
  mongodb:
    image: "mongo:5.0"
    volumes:
      - "mongodb_data:/data/db"
    # Other options are "on-failure" and "no"  
    restart: "always"

  opensearch:
    image: "opensearchproject/opensearch:2.4.0"
    environment:
      - "${OPENSEARCH_JAVA_OPTS}"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "action.auto_create_index=false"
      - "plugins.security.ssl.http.enabled=false"
      - "plugins.security.disabled=true"
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
      - "os_data:/usr/share/opensearch/data"
    # Other options are "on-failure" and "no"  
    restart: "always"

  graylog:
    hostname: "server"
    image: "${GRAYLOG_IMAGE:-graylog/graylog:5.0}"
    depends_on:
      opensearch:
        condition: "service_started"
      mongodb:
        condition: "service_started"
    entrypoint: "/usr/bin/tini -- wait-for-it opensearch:9200 --  /docker-entrypoint.sh"
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/config/node-id"
      GRAYLOG_PASSWORD_SECRET: "${GRAYLOG_PASSWORD_SECRET:?Please configure GRAYLOG_PASSWORD_SECRET in the .env file}"
      GRAYLOG_ROOT_PASSWORD_SHA2: "${GRAYLOG_ROOT_PASSWORD_SHA2:?Please configure GRAYLOG_ROOT_PASSWORD_SHA2 in the .env file}"
      GRAYLOG_ROOT_EMAIL: "${GRAYLOG_ROOT_EMAIL:?Please configure GRAYLOG_ROOT_EMAIL in the .env file}"
      GRAYLOG_ROOT_TIMEZONE: "Europe/Berlin"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9000/"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://opensearch:9200"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
      GRAYLOG_TRANSPORT_EMAIL_WEB_INTERFACE_URL: "${GRAYLOG_TRANSPORT_EMAIL_WEB_INTERFACE_URL:?Please configure GRAYLOG_TRANSPORT_EMAIL_WEB_INTERFACE_URL in the .env file}"
      GRAYLOG_TRANSPORT_EMAIL_HOSTNAME: "${GRAYLOG_TRANSPORT_EMAIL_HOSTNAME:?Please configure GRAYLOG_TRANSPORT_EMAIL_HOSTNAME in the .env file}"
      GRAYLOG_TRANSPORT_EMAIL_ENABLED: true
      GRAYLOG_TRANSPORT_EMAIL_PORT: "25"
      GRAYLOG_TRANSPORT_EMAIL_USE_AUTH: "false"
      GRAYLOG_TRANSPORT_EMAIL_USE_TLS: "false"
      GRAYLOG_TRANSPORT_EMAIL_USE_SSL: "false"
      GRAYLOG_TRANSPORT_EMAIL_FROM_EMAIL: "${GRAYLOG_TRANSPORT_EMAIL_FROM_EMAIL:?Please configure GRAYLOG_TRANSPORT_EMAIL_FROM_EMAIL in the .env file}"
      GRAYLOG_TRANSPORT_SUBJECT_PREFIX: "[graylog]"
      # To make reporting (headless_shell) work inside a Docker container
      GRAYLOG_REPORT_DISABLE_SANDBOX: "true"
    ports:
    - "5044:5044/tcp"   # Beats
    - "5515:5515/tcp"   # Syslog TCP
    - "5514:5514/udp"   # Syslog UDP
    - "5555:5555/tcp"   # RAW TCP
    - "5555:5555/udp"   # RAW TCP
    - "9000:9000/tcp"   # Server API
    - "12201:12201/tcp" # GELF TCP
    - "12201:12201/udp" # GELF UDP
    #- "10000:10000/tcp" # Custom TCP port
    #- "10000:10000/udp" # Custom UDP port
    - "13301:13301/tcp" # Forwarder data
    - "13302:13302/tcp" # Forwarder config
    volumes:
      - "graylog_data:/usr/share/graylog/data/data"
      - "graylog_journal:/usr/share/graylog/data/journal"
    # Other options are "on-failure" and "no"  
    restart: "always"

volumes:
  mongodb_data:
    driver: local
  os_data:
    driver: local
  graylog_data:
    driver: local
  graylog_journal:
    driver: local
